services:
  db:
    image: postgres:16-bookworm
    container_name: barberkuy-db
    environment:
      POSTGRES_USER: barberkuy
      POSTGRES_PASSWORD: barberkuy
      POSTGRES_DB: barberkuy
    ports:
      - '5433:5432'
    volumes:
      - barberkuy-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U barberkuy']
      interval: 3s
      timeout: 3s
      retries: 20

volumes:
  barberkuy-pgdata:
